/** @type {import('tailwindcss').Config} */
export default {
	content: [
		'./pages/**/*.{ts,tsx}',
		'./components/**/*.{ts,tsx}',
		'./app/**/*.{ts,tsx}',
		'./src/**/*.{ts,tsx}',
	],
	// darkMode: ["selector", '[data-theme="dark"]', "class"],
	darkMode: ['class'],
	plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
	prefix: '',
	safelist: [
		'lg:col-span-4',
		'lg:col-span-6',
		'lg:col-span-8',
		'lg:col-span-12',
		'border-border',
		'bg-card',
		'border-error',
		'bg-error/30',
		'border-success',
		'bg-success/30',
		'border-warning',
		'bg-warning/30',
	],
	theme: {
		container: {
			center: true,
			padding: {
				'2xl': '2rem',
				DEFAULT: '1rem',
				lg: '2rem',
				md: '2rem',
				sm: '1rem',
				xl: '2rem',
			},
			screens: {
				'2xl': '86rem',
				lg: '64rem',
				md: '48rem',
				sm: '40rem',
				xl: '80rem',
			},
		},
		extend: {
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
				float: 'float 3s ease-in-out infinite',
				'book-entrance': 'book-entrance 1200ms ease-in-out forwards',
				'bubble-fade-in': 'bubble-fade-in 700ms ease-out forwards',
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			colors: {
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				background: 'hsl(var(--background))',
				border: 'hsla(var(--border))',
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				foreground: 'hsl(var(--foreground))',
				input: 'hsl(var(--input))',
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				ring: 'hsl(var(--ring))',
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				success: 'hsl(var(--success))',
				error: 'hsl(var(--error))',
				warning: 'hsl(var(--warning))',
				vercel: {
					100: 'var(--ds-background-100)',
					200: 'var(--ds-background-200)',
				},
				sidebar: {
					DEFAULT: 'hsl(var(--sidebar-background))',
					foreground: 'hsl(var(--sidebar-foreground))',
					primary: 'hsl(var(--sidebar-primary))',
					'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
					accent: 'hsl(var(--sidebar-accent))',
					'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
					border: 'hsl(var(--sidebar-border))',
					ring: 'hsl(var(--sidebar-ring))',
				},
				// Design System Colors
				ds: {
					gray: {
						100: 'var(--ds-gray-100)',
						200: 'var(--ds-gray-200)',
						300: 'var(--ds-gray-300)',
						400: 'var(--ds-gray-400)',
						500: 'var(--ds-gray-500)',
						600: 'var(--ds-gray-600)',
						700: 'var(--ds-gray-700)',
						800: 'var(--ds-gray-800)',
						900: 'var(--ds-gray-900)',
						1000: 'var(--ds-gray-1000)',
					},
					blue: {
						100: 'var(--ds-blue-100)',
						200: 'var(--ds-blue-200)',
						300: 'var(--ds-blue-300)',
						400: 'var(--ds-blue-400)',
						500: 'var(--ds-blue-500)',
						600: 'var(--ds-blue-600)',
						700: 'var(--ds-blue-700)',
						800: 'var(--ds-blue-800)',
						900: 'var(--ds-blue-900)',
						1000: 'var(--ds-blue-1000)',
					},
					red: {
						100: 'var(--ds-red-100)',
						200: 'var(--ds-red-200)',
						300: 'var(--ds-red-300)',
						400: 'var(--ds-red-400)',
						500: 'var(--ds-red-500)',
						600: 'var(--ds-red-600)',
						700: 'var(--ds-red-700)',
						800: 'var(--ds-red-800)',
						900: 'var(--ds-red-900)',
						1000: 'var(--ds-red-1000)',
					},
					amber: {
						100: 'var(--ds-amber-100)',
						200: 'var(--ds-amber-200)',
						300: 'var(--ds-amber-300)',
						400: 'var(--ds-amber-400)',
						500: 'var(--ds-amber-500)',
						600: 'var(--ds-amber-600)',
						700: 'var(--ds-amber-700)',
						800: 'var(--ds-amber-800)',
						900: 'var(--ds-amber-900)',
						1000: 'var(--ds-amber-1000)',
					},
					green: {
						100: 'var(--ds-green-100)',
						200: 'var(--ds-green-200)',
						300: 'var(--ds-green-300)',
						400: 'var(--ds-green-400)',
						500: 'var(--ds-green-500)',
						600: 'var(--ds-green-600)',
						700: 'var(--ds-green-700)',
						800: 'var(--ds-green-800)',
						900: 'var(--ds-green-900)',
						1000: 'var(--ds-green-1000)',
					},
					teal: {
						100: 'var(--ds-teal-100)',
						200: 'var(--ds-teal-200)',
						300: 'var(--ds-teal-300)',
						400: 'var(--ds-teal-400)',
						500: 'var(--ds-teal-500)',
						600: 'var(--ds-teal-600)',
						700: 'var(--ds-teal-700)',
						800: 'var(--ds-teal-800)',
						900: 'var(--ds-teal-900)',
						1000: 'var(--ds-teal-1000)',
					},
					purple: {
						100: 'var(--ds-purple-100)',
						200: 'var(--ds-purple-200)',
						300: 'var(--ds-purple-300)',
						400: 'var(--ds-purple-400)',
						500: 'var(--ds-purple-500)',
						600: 'var(--ds-purple-600)',
						700: 'var(--ds-purple-700)',
						800: 'var(--ds-purple-800)',
						900: 'var(--ds-purple-900)',
						1000: 'var(--ds-purple-1000)',
					},
					pink: {
						100: 'var(--ds-pink-100)',
						200: 'var(--ds-pink-200)',
						300: 'var(--ds-pink-300)',
						400: 'var(--ds-pink-400)',
						500: 'var(--ds-pink-500)',
						600: 'var(--ds-pink-600)',
						700: 'var(--ds-pink-700)',
						800: 'var(--ds-pink-800)',
						900: 'var(--ds-pink-900)',
						1000: 'var(--ds-pink-1000)',
					},
				},
			},
			fontFamily: {
				mono: ['var(--font-geist-mono)'],
				sans: ['var(--font-geist-sans)'],
			},
			keyframes: {
				'accordion-down': {
					from: {
						height: '0',
					},
					to: {
						height: 'var(--radix-accordion-content-height)',
					},
				},
				'accordion-up': {
					from: {
						height: 'var(--radix-accordion-content-height)',
					},
					to: {
						height: '0',
					},
				},
				float: {
					'0%, 100%': { transform: 'translateY(0)' },
					'50%': { transform: 'translateY(2px)' },
				},
				'book-entrance': {
					'0%': { transform: 'translateY(400px) rotate(-24deg)' },
					'100%': { transform: 'translateY(0) rotate(6deg)' },
				},
				'bubble-fade-in': {
					'0%': { opacity: '0', filter: 'blur(5px)' },
					'100%': { opacity: '1', filter: 'blur(0)' },
				},
			},
			typography: ({ theme }) => ({
				vercel: {
					css: {
						'--tw-prose-body': theme('colors.ds.gray.1000'),
						'--tw-prose-headings': theme('colors.ds.gray.1000'),
						'--tw-prose-lead': theme('colors.ds.gray.1000'),
						'--tw-prose-links': theme('colors.geist.link'),
						'--tw-prose-bold': theme('colors.ds.gray.1000'),
						'--tw-prose-counters': theme('colors.ds.gray.900'),
						'--tw-prose-bullets': theme('colors.ds.gray.900'),
						'--tw-prose-hr': theme('colors.ds.gray.200'),
						'--tw-prose-quotes': theme('colors.ds.gray.1000'),
						'--tw-prose-quote-borders': theme('colors.ds.gray.300'),
						'--tw-prose-captions': theme('colors.ds.gray.900'),
						'--tw-prose-code': theme('colors.ds.gray.1000'),
						'--tw-prose-pre-code': theme('colors.ds.gray.100'),
						'--tw-prose-pre-bg': theme('colors.white'),
						'--tw-prose-th-borders': theme('colors.ds.gray.200'),
						'--tw-prose-td-borders': theme('colors.ds.gray.200'),
						h1: {
							fontWeight: theme('fontWeight.semibold'),
							color: theme('colors.ds.gray.1000'),
							scrollMarginTop: '51px',
						},
						h2: {
							fontWeight: theme('fontWeight.semibold'),
							scrollMarginTop: '51px',
						},
						'h2:not(:is(h1 + h2))': {
							borderTopStyle: 'solid',
							borderTopWidth: '1px',
							borderColor: theme('colors.ds.gray.200'),
							paddingTop: theme('spacing[10]'),
							scrollMarginTop: '11px',
						},
						h3: {
							fontWeight: theme('fontWeight.semibold'),
							scrollMarginTop: '51px',
						},
						h4: {
							fontWeight: theme('fontWeight.semibold'),
							scrollMarginTop: '51px',
						},
						h5: {
							fontWeight: theme('fontWeight.semibold'),
							scrollMarginTop: '51px',
						},
						h6: {
							fontWeight: theme('fontWeight.medium'),
							scrollMarginTop: '51px',
						},
						'[data-docs-heading]': {
							a: {
								color: 'inherit',
								span: {
									display: 'inline-flex',
									marginLeft: theme('spacing[1.5]'),
									visibility: 'hidden',
									opacity: 0,
								},
								'&:hover': {
									span: {
										visibility: 'visible',
										opacity: 100,
									},
								},
							},
						},
						a: {
							textDecoration: 'none',
							fontWeight: 'inherit',
						},
						code: {
							fontWeight: 'inherit',
							backgroundColor: theme('colors.ds.gray.100'),
							borderRadius: theme('borderRadius.md'),
							borderWidth: '1px',
							borderColor: theme('colors.ds.gray.200'),
							paddingTop: theme('padding[0.5]'),
							paddingBottom: theme('padding[0.5]'),
							paddingLeft: theme('padding[1]'),
							paddingRight: theme('padding[1]'),
							'&::before': {
								content: 'none',
							},
							'&::after': {
								content: 'none',
							},
						},
						blockquote: {
							backgroundColor: theme('colors.vercel[100]'),
							borderWidth: theme('borderWidth.DEFAULT'),
							borderColor: theme('colors.ds.gray.200'),
							borderRadius: theme('borderRadius.md'),
							fontStyle: 'normal',
							fontWeight: 'normal',
							padding: theme('padding[6]'),
							p: {
								marginTop: theme('margin[0]'),
								marginBottom: theme('margin[2]'),
								'&:last-child': {
									marginBottom: theme('margin[0]'),
								},
								'&::before': {
									content: 'none',
								},
								'&::after': {
									content: 'none',
								},
							},
							ul: {
								marginTop: theme('margin[2]'),
								marginBottom: theme('margin[2]'),
							},
						},
						details: {
							summary: {
								cursor: 'pointer',
								fontWeight: theme('fontWeight.semibold'),
								userSelect: 'none',
							},
						},
					},
				},
			}),
		},
	},
}
